export const CAROUSEL_DATA = [
  { src: 'src/assets/images/home_img_scroll_01.png', alt: 'image1' },
  { src: 'src/assets/images/home_img_scroll_02.png', alt: 'image2' },
  { src: 'src/assets/images/home_img_scroll_03.png', alt: 'image3' },
  { src: 'src/assets/images/home_img_scroll_04.png', alt: 'image4' },
  { src: 'src/assets/images/home_img_scroll_05.png', alt: 'image5' },
  { src: 'src/assets/images/home_img_scroll_06.png', alt: 'image6' },
  { src: 'src/assets/images/home_img_scroll_01.png', alt: 'image7' },
  { src: 'src/assets/images/home_img_scroll_02.png', alt: 'image8' },
  { src: 'src/assets/images/home_img_scroll_03.png', alt: 'image9' },
  { src: 'src/assets/images/home_img_scroll_04.png', alt: 'image10' },
  { src: 'src/assets/images/home_img_scroll_05.png', alt: 'image11' },
  { src: 'src/assets/images/home_img_scroll_06.png', alt: 'image12' },
  { src: 'src/assets/images/home_img_scroll_01.png', alt: 'image13' },
  { src: 'src/assets/images/home_img_scroll_02.png', alt: 'image14' },
  { src: 'src/assets/images/home_img_scroll_03.png', alt: 'image15' },
  { src: 'src/assets/images/home_img_scroll_04.png', alt: 'image16' },
  { src: 'src/assets/images/home_img_scroll_05.png', alt: 'image17' },
  { src: 'src/assets/images/home_img_scroll_06.png', alt: 'image18' },
];
