import img1 from '@/assets/images/Card_pic.png';

export const CULTURE_DATA = {
  categories: [
    {
      name: 'space',
      cultures: [
        {
          id: 1,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 2,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 3,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 4,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 5,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 6,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 7,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 8,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 9,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
      ],
    },
    {
      name: 'culture',
      cultures: [
        {
          id: 10,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 11,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 12,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 13,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 14,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 15,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 16,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 17,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
        {
          id: 18,
          description: '바이닐로 듣는 아날로그 음악의 울림',
          image: img1,
          name: 'BONUS TRACK 13.김사월',
          summary: '보편적 감성을 자극하는 한극 포크의 새 모델',
          period: '2024.04.01 ~ 2024.05.01',
        },
      ],
    },
  ],
};
