export const CATEGORY_BOX_DATA = {
  HYUNDAI: '현대카드의 오리지널리티를 담은 진정한 현대카드',
  CHAMPION: '현대카드의 오리지널리티를 담은 진정한 현대카드',
  BUSINESS: '현대카드 혜택을 더한 개인사업자 전용카드',
};

export const CHECK_BOX_DATA = [
  {
    categoryName: 'Hyundai Originals',
    checkboxes: [
      { title: 'All' },
      { title: 'Premium' },
      { title: 'M' },
      { title: 'X' },
      { title: 'Z' },
      { title: 'ZERO' },
    ],
  },
  {
    categoryName: 'Champion Brands',
    checkboxes: [
      { title: 'All' },
      { title: 'Premium' },
      { title: 'M' },
      { title: 'X' },
      { title: 'Z' },
      { title: 'ZERO' },
    ],
  },
  {
    categoryName: '제휴카드',
    checkboxes: [
      { title: 'All' },
      { title: 'Premium' },
      { title: 'M' },
      { title: 'X' },
      { title: 'Z' },
      { title: 'ZERO' },
    ],
  },
  {
    categoryName: 'My Business',
    checkboxes: [
      { title: 'All' },
      { title: 'Premium' },
      { title: 'M' },
      { title: 'X' },
      { title: 'Z' },
      { title: 'ZERO' },
    ],
  },
];

export const CARD_DATA = [
  {
    category: 'hyundai-originals',
    card: [
      {
        id: 1,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: true,
        tags: ['All', 'Hi'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 2,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Hi'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 3,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 4,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 5,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 6,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
    ],
  },
  {
    category: 'Champion-Brands',
    card: [
      {
        id: 7,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 8,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 9,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
    ],
  },
  {
    category: '제휴카드',
    card: [
      {
        id: 10,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 11,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 12,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
    ],
  },
  {
    category: 'My Business',
    card: [
      {
        id: 13,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 14,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
      {
        id: 15,
        cardTitle: 'the Black Edition3',
        cardSrc: 'src/assets/images/img_card.png',
        cardTarget: 'Invitation Only',
        cardInfo: '단 1,000명에게 선사하는 VVIP 카드',
        hasEvent: false,
        tags: ['All', 'Premium'],
        hoverInfo1: 50000,
        hoverInfo2: 50000,
      },
    ],
  },
];
